DROP TABLE IF EXISTS USR;

CREATE TABLE USR
(
    ID long NOT NULL,
    FIRST_NAME varchar(255),
    FAMILY_NAME varchar(255),
    VERSION int NOT NULL,
    LAST_UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID),
) ;